CREATE TABLE `equalto`.`equalto_vision17_users` (
  `uID` INT NOT NULL auto_increment ,
  `email` VARCHAR(200) UNIQUE,
  `startTime` bigint,
  `endTime` bigint,
  `count` INT NOT NULL default 0,
  `score` INT NOT NULL default 0,
  `q1` INT default NULL,
  `q2` INT default NULL,
  `q3` INT default NULL,
  `q4` INT default NULL,
  `q5` INT default NULL,
  `q6` INT default NULL,
  `q7` INT default NULL,
  `q8` INT default NULL,
  `q9` INT default NULL,
  `q10` INT default NULL,
  `q11` INT default NULL,
  `q12` INT default NULL,
  `q13` INT default NULL,
  `q14` INT default NULL,
  `q15` INT default NULL,
  PRIMARY KEY (`uID`));